# Generated by Django 4.2.4 on 2023-08-14 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.TextField()),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 13, 36, 0, 434048))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook_v22.user')),
            ],
        ),
    ]
