# Generated by Django 4.2.4 on 2023-08-16 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_v22', '0003_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook_v22.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook_v22.user')),
            ],
        ),
    ]
